import { useCallback, useEffect, useMemo, useState } from "react";
import ReactMarkdown from "react-markdown";
import apiFetch from "../lib/api";

const SECTION_LABELS = {
  overview: "Overview",
  architecture: "Architecture",
  api: "API",
  modules: "Modules",
  setup: "Setup",
  contributing: "Contributing",
};

const SECTION_DESCRIPTIONS = {
  overview: "What the project is, its languages, and aggregate stats.",
  architecture: "Layered structure, hub files, directories, and external dependencies.",
  api: "Route/controller files and their exported handlers.",
  modules: "Per-directory purpose summaries inferred from imports/exports.",
  setup: "Install, run, test, and lint commands plus env template files.",
  contributing: "How to contribute — branching, code style, tests, PR checklist.",
};

function Markdown({ children }) {
  return (
    <div className="docs-md prose-sm max-w-none">
      <ReactMarkdown>{children}</ReactMarkdown>
    </div>
  );
}

export default function DocsTab({ repoId, repoName }) {
  const [sections, setSections] = useState([]);
  const [activeSection, setActiveSection] = useState("overview");
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [regenerating, setRegenerating] = useState(null);
  const [confirmRegen, setConfirmRegen] = useState(null);
  const [error, setError] = useState(null);

  const loadDocs = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await apiFetch(`/api/repos/${repoId}/docs`);
      setSections(data.sections || []);
      const firstGenerated = (data.sections || []).find((s) => s.content);
      if (firstGenerated) setActiveSection(firstGenerated.sectionType);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }, [repoId]);

  useEffect(() => {
    loadDocs();
  }, [loadDocs]);

  const byType = useMemo(() => {
    const map = {};
    for (const s of sections) map[s.sectionType] = s;
    return map;
  }, [sections]);

  const hasAny = sections.some((s) => s.content);
  const active = byType[activeSection] || { sectionType: activeSection, content: null, sourceFiles: [], generatedAt: null };
  const generatedCount = sections.filter((s) => s.content).length;

  async function handleGenerateAll() {
    setGenerating(true);
    setError(null);
    try {
      await apiFetch(`/api/repos/${repoId}/docs/generate`, { method: "POST" });
      await loadDocs();
    } catch (e) {
      setError(e.message);
    } finally {
      setGenerating(false);
    }
  }

  async function handleRegenerate() {
    if (!confirmRegen) return;
    setRegenerating(confirmRegen);
    setError(null);
    try {
      await apiFetch(`/api/repos/${repoId}/docs/${confirmRegen}/regenerate`, { method: "POST" });
      setConfirmRegen(null);
      await loadDocs();
    } catch (e) {
      setError(e.message);
      setConfirmRegen(null);
    } finally {
      setRegenerating(null);
    }
  }

  function handleExport() {
    const parts = [`# ${repoName} — Generated Documentation`, "", `Generated by CodeLens (${new Date().toLocaleString()})`, ""];
    for (const s of sections) {
      if (!s.content) continue;
      parts.push(`---`, "", `## ${SECTION_LABELS[s.sectionType] || s.sectionType}`, "", s.content, "");
    }
    const blob = new Blob([parts.join("\n")], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${(repoName || "repository").replace(/[/\\]/g, "-")}-docs.md`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="mt-4">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h2 className="text-lg font-semibold">Documentation</h2>
          <p className="mt-1 max-w-2xl text-xs text-gray-500">
            Up to 6 sections generated by Gemini, each grounded in repository analysis data ({SECTION_LABELS.overview}, {SECTION_LABELS.architecture}, {SECTION_LABELS.api}, {SECTION_LABELS.modules}, {SECTION_LABELS.setup}, {SECTION_LABELS.contributing}). Cached sections are reused until the repo is re-analyzed.
          </p>
        </div>
        <div className="flex gap-2">
          {hasAny && (
            <button
              onClick={handleExport}
              className="rounded-lg border border-gray-700 px-4 py-2 text-sm font-medium text-gray-300 hover:bg-gray-900"
            >
              Export as Markdown
            </button>
          )}
          <button
            onClick={handleGenerateAll}
            disabled={generating}
            className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-gray-950 transition hover:bg-gray-200 disabled:opacity-50"
          >
            {generating ? "Generating…" : "Generate Documentation"}
          </button>
        </div>
      </div>

      {error && (
        <div className="mt-4 rounded-lg border border-red-900 bg-red-950/40 px-4 py-3 text-sm text-red-300">
          {error}
        </div>
      )}

      {generating && (
        <div className="mt-4 rounded-lg border border-amber-900/60 bg-amber-950/30 px-6 py-8 text-center">
          <p className="text-sm font-medium text-amber-300">
            Generating up to 6 documentation sections…
          </p>
          <p className="mt-2 text-xs text-amber-400/70">
            Each section is a separate Gemini call, run sequentially. This can take a minute.
          </p>
        </div>
      )}

      {!loading && !hasAny && !generating && (
        <div className="mt-6 rounded-lg border border-gray-800 bg-gray-950 px-6 py-10 text-center">
          <p className="text-sm text-gray-400">No documentation generated yet.</p>
          <p className="mt-1 text-xs text-gray-600">
            Generate all 6 sections with one call — cached results are reused on subsequent runs.
          </p>
        </div>
      )}

      {!loading && hasAny && (
        <>
          <div className="mt-4 flex flex-wrap gap-1 border-b border-gray-800 pb-px">
            {sections.map((s) => (
              <button
                key={s.sectionType}
                onClick={() => setActiveSection(s.sectionType)}
                className={`border-b-2 px-4 py-2 text-sm font-medium transition ${
                  activeSection === s.sectionType
                    ? "border-white text-white"
                    : s.content
                      ? "border-transparent text-gray-400 hover:text-gray-200"
                      : "border-transparent text-gray-600"
                }`}
              >
                {SECTION_LABELS[s.sectionType] || s.sectionType}
                {s.content && (
                  <span className="ml-2 inline-block h-1.5 w-1.5 rounded-full bg-green-500 align-middle" />
                )}
              </button>
            ))}
          </div>

          <div className="mt-4 grid grid-cols-2 gap-x-6 gap-y-3 rounded-lg border border-gray-800 bg-gray-900 p-4 text-sm sm:grid-cols-3">
            {sections.map((s) => (
              <div key={s.sectionType}>
                <p className="text-xs text-gray-500">{SECTION_LABELS[s.sectionType]}</p>
                <p className="mt-0.5 font-medium text-gray-200">
                  {s.content ? "Generated" : "Not generated"}
                </p>
              </div>
            ))}
          </div>

          <div className="mt-6 overflow-hidden rounded-lg border border-gray-800 bg-gray-950">
            <div className="flex flex-wrap items-center justify-between gap-3 border-b border-gray-800 bg-gray-900 px-4 py-3">
              <div>
                <p className="text-sm font-semibold text-white">
                  {SECTION_LABELS[active.sectionType]}
                </p>
                <p className="mt-0.5 text-xs text-gray-500">
                  {SECTION_DESCRIPTIONS[active.sectionType]}
                </p>
              </div>
              <button
                onClick={() => setConfirmRegen(active.sectionType)}
                disabled={regenerating === active.sectionType}
                className="rounded-lg border border-amber-800 px-3 py-1.5 text-xs font-medium text-amber-300 hover:bg-amber-950/50 disabled:opacity-50"
              >
                {regenerating === active.sectionType ? "Regenerating…" : "Regenerate"}
              </button>
            </div>

            {confirmRegen === active.sectionType && (
              <div className="flex flex-wrap items-center justify-between gap-3 border-b border-amber-900/60 bg-amber-950/30 px-4 py-3 text-xs text-amber-300">
                <p>Regenerating this section will call Gemini again. Continue?</p>
                <div className="flex gap-2">
                  <button
                    onClick={handleRegenerate}
                    disabled={regenerating === active.sectionType}
                    className="rounded-lg bg-amber-600 px-3 py-1.5 font-medium text-amber-950 hover:bg-amber-500 disabled:opacity-50"
                  >
                    Regenerate
                  </button>
                  <button
                    onClick={() => setConfirmRegen(null)}
                    className="rounded-lg border border-amber-800 px-3 py-1.5 hover:bg-amber-950/50"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            )}

            <div className="p-4">
              {active.content ? (
                <>
                  <Markdown>{active.content}</Markdown>
                  {(active.sourceFiles || []).length > 0 && (
                    <div className="mt-6 border-t border-gray-800 pt-3">
                      <p className="text-[11px] font-semibold uppercase tracking-wide text-gray-500">
                        Grounded in {active.sourceFiles.length} source file(s)
                      </p>
                      <div className="mt-2 flex flex-wrap gap-1">
                        {active.sourceFiles.map((f) => (
                          <span key={f} className="rounded bg-gray-800 px-1.5 py-0.5 font-mono text-[10px] text-gray-400">
                            {f}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                  {active.generatedAt && (
                    <p className="mt-3 text-[11px] text-gray-600">
                      Generated {new Date(active.generatedAt).toLocaleString()} · {generatedCount}/{sections.length} sections
                    </p>
                  )}
                </>
              ) : (
                <p className="py-10 text-center text-sm text-gray-500">
                  This section has not been generated yet. Click "Generate Documentation" or use "Regenerate" to create it.
                </p>
              )}
            </div>
          </div>
        </>
      )}
    </div>
  );
}